### ISSUE TITLE
【elasticsearch】helm install elastic/elasticsearch.

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#1]
display 0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.

elasticsearch.antiAffinity="hard"， change to "".

**Comment by yaphetsglhf** [comment]
how to enable xpack in es 7.6.0

**Comment by yaphetsglhf** [comment]
still not work, pods running, but can not turn status to ready. go on debugginng.

**Comment by yaphetsglhf** [comment]
if you enable `xpack`, remember to set the protocol to `https`.

**Comment by yaphetsglhf** [comment]
refer to `https://github.com/elastic/helm-charts/issues/587`

**Comment by yaphetsglhf** [comment]
refer to` https://github.com/elastic/helm-charts/issues/587#issuecomment-621784754`

decode secret "elastic-certificate-pem".
save the private key to tls.key and certificate to tls.crt.
create a TLS secret with name logstash-certificate for example as the following
kubectl create secret tls logstash-certificate-pem --key="tls.key" --cert="tls.crt
edit values.yaml as the following

```
secretMounts:
      - name: logstash-certificate-pem
        secretName: logstash-certificate-pem
        path: /usr/share/logstash/config/certs
    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.enabled: true

    logstashPipeline:
      uptime.conf: |
        input { exec { command => "uptime" interval => 30 } }
        output { elasticsearch { hosts => ["https://security-master:9200"] user => "elastic" password => "password" index => "uptime" ssl_certificate_verification => false cacert => "/usr/share/logstash/config/certs/tls.crt"} }
```
