### ISSUE TITLE
【kong】helm install kong, kong init migration failed

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#16]
/bin/sh: KONG_PG_HOST: parameter not set

**Comment by yaphetsglhf** [comment]
init command like:
```
/bin/sh
      -c
      set -u; until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo "waiting for db - trying ${KONG_PG_HOST}:${KONG_PG_PORT}"; sleep 1; done
```

**Comment by yaphetsglhf** [comment]
check the env:
```
Environment:
      KONG_ADMIN_ACCESS_LOG:        /dev/stdout
      KONG_ADMIN_ERROR_LOG:         /dev/stderr
      KONG_ADMIN_GUI_ACCESS_LOG:    /dev/stdout
      KONG_ADMIN_GUI_ERROR_LOG:     /dev/stderr
      KONG_ADMIN_LISTEN:            0.0.0.0:8444 ssl http2
      KONG_DATABASE:                postgres
      KONG_KONG_PG_HOST:            http://gateway-kong-admin
```
KONG_PG_HOST has a prefix kong. change the env variable

**Comment by yaphetsglhf** [comment]
```
 database: "postgres"
    pg_database: "kong"
    pg_host: "gateway-postgresql"
    pg_user: "tiny"
    pg_password:
      valueFrom:
           secretKeyRef:
              key: "postgresql-password"
              name: "gateway-postgresql"
    createSecret: true
    postgresqlUsername: "xxxx"
    postgresqlPassword: "xxxx"
    postgresqlDatabase: "kong"
```

refer to `https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run` for details.

**Comment by yaphetsglhf** [comment]
post the whole yaml
```
# Default values for gateways.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  postgresql:
    existingSecret: ""
    # existingSecret: "gateway-postgresql"

kong:
  env:
    database: "postgres"
    pg_database: "kong"
    pg_host: "gateway-postgresql"
    pg_user: "kong"
    pg_password:
      valueFrom:
           secretKeyRef:
              key: "postgresql-password"
              name: "gateway-postgresql"
    pg_port: 5432
  proxy:
    enabled: true
  admin:
    enabled: true
  podDisruptionBudget:
    enabled: true
    maxUnavailable: "50%"
  ingressController:
    installCRDs: false
  postgresql:
    persistence:
      enabled: true
      storageClass: "alicloud-disk-efficiency"
      size: 20Gi
    postgresqlUsername: "kong"
    postgresqlPassword: "t1ny.c0m"
    postgresqlDatabase: "kong"
```
pay attention:
```
1. first time. you shoud set the global.postgresql.existingSecret="", then helm will create secret for you, then you should set the existingSecret to the secret name
2. kong.postgresql is where you config the postgresql, not parallel with kong.
```
