### ISSUE TITLE
【kong】oauth2.0 failed with authorization_code

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#22]
makefile like this:
```
kong:=127.0.0.1
service:=bffql
url:=http://localhost:8080

# change everytime
consumer_id:=c80f871d-4626-472a-bb2f-b7e688e616af
provision_key:=HiqGOFt6AOWU1lPtoClYuwBevi1hqYuG
client_id:=Bqq4Gl7oXiZUPWAmerRIHa71vquKIFdA

ping:
	curl -X GET http://localhost:8000/bffql

service:
	curl -X POST \
	  --url "http://${kong}:8001/services" \
	  --data "name=${service}" \
	  --data "url=${url}"

route:
	curl -X POST \
	  --url "http://${kong}:8001/services/${service}/routes" \
	  --data "paths=/bffql"

oauth2:
	curl -X POST http://${kong}:8001/services/${service}/plugins \
		--data "name=oauth2"  \
		--data "enabled=true" \
		--data "config.mandatory_scope=false" \
		--data "config.enable_authorization_code=true" \
		--data "config.enable_client_credentials=true" \
		--data "config.auth_header_name=authorization" \
		--data "config.refresh_token_ttl=604800" \
		--data "config.token_expiration=7200" \
		--data "config.accept_http_if_already_terminated=true" 

consumer:
	curl -X POST http://${kong}:8001/consumers/ \
		--data "custom_id=1"

app:
	echo "Pay attention to consumer_id."
	curl -X POST http://${kong}:8001/consumers/${consumer_id}/oauth2 \
		--data "name=${service}" \
		--data "redirect_uris=http://www.baidu.com"

code:
	curl -X POST http://${kong}:8000/bffql/oauth2/authorize \
		 -H "X-Forwarded-Proto=https" \
		--data "response_type=code" \
		--data "client_id=${client_id}" \
		--data "provision_key=${provision_key}" 

```
{"error_description":"You must use HTTPS","error":"access_denied"}

**Comment by yaphetsglhf** [comment]
docker-compose.yml
```
version: "3.7"

services:
  bffql:
    build: .
    image: "bffql"
    container_name: "bffql"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default
      - tiny
    env_file:
      - .env
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn"
    expose:
      - "8080"
    command: ["go", "run", "main.go"]
    restart: always
    networks:
      - tiny
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms16M"
    networks:
      - tiny
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - tiny
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: "kong"
    networks:
      - tiny
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: "kong"
    networks:
      - tiny
    restart: on-failure
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_TRUSTED_IPS: "0.0.0.0/0"
    networks:
      - tiny
    ports:
      - "8000:8000/tcp"
      - "0.0.0.0:8001:8001/tcp"
      - "8443:8443/tcp"
      - "0.0.0.0:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: "kong"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - tiny
    # volumes:
    #   - kong_data:/var/lib/postgresql/data
networks:
  tiny:
    external: true
# volumes:
#   kong_data: {}
```
