### ISSUE TITLE
【helm】error: nil pointer evaluating interface {}.labels

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#26]
here is my values.yaml
```
labels:
  tier: base
  release: stable 
  service: &service base 
```
