### ISSUE TITLE
【helm】helm install error with configmap

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#28]
`Error: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found f, error found in #10 byte of ...|OG_MODE":false`

**Comment by yaphetsglhf** [comment]
configmap.yaml looks like: 
```
    envs:
      ACCOUNT_SERVICE: "http://accountservice:9090"
      GORM_LOG_MODE: false
      GIN_MODE: "release"
      KAFKA_HOST: "kafka:9092"
```

**Comment by yaphetsglhf** [comment]
double quote false, it works.
```
    envs:
      ACCOUNT_SERVICE: "http://accountservice:9090"
      GORM_LOG_MODE: "false"
      GIN_MODE: "release"
      KAFKA_HOST: "kafka:9092"
```
