### ISSUE TITLE
【helm】Chart.yaml not work with condition function.

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#31]
```
dependencies:
- name: mysql
  version: "1.6.2"
  repository: "file://charts/mysql"
  condition: mysql.enabled
- name: redis
  version: "10.5.7"
  repository: "file://charts/redis"
  condition: redis.enabled
```
even i set redis.enabled=false, redis will still bootstrap.

**Comment by yaphetsglhf** [comment]
```
dependencies:
  - name: cdc
    repository: "@infra"
    version: 0.1.0
    condition: cdc.enabled
  - name: kafka
    repository: "@infra"
    version: 0.1.0
    condition: kafka.enabled
```
it works, just match the version. it's the chart version. not the app verison
