### ISSUE TITLE
【istio】jobs will not complete

### ISSUE THREAD

**Issue by yaphetsglhf** [yaphetsglhf/issues#52]
It's running always the time, will not complete.

**Comment by yaphetsglhf** [comment]
A Job is not considered complete until all containers have stopped running, and Istio Sidecars run indefinitely. that's the promlem. so disable the injection with job in istio solve the problem.
```
spec:
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
```

Any solutions see https://medium.com/redbox-techblog/handling-istio-sidecars-ain-kubernetes-jobs-c392661c4af7
